preload:
  artifacts:
    - "se.scalablesolutions.akka:akka-actor:1.3.1"
    - "se.scalablesolutions.akka:akka-remote:1.3.1"
  maven_repositories:
    - typesafe:
        layout: default
        url: http://repo.typesafe.com/typesafe/releases/
